### PR TITLE
#10 Docker Container

### LINKED ISSUE #10: Docker Container
### Summary

A Docker Container that works effectively in Linux, Unix and Windows systems.

### Requirements

- Must update the .travis.yml file with passing build configurations for Linux, Unix, and Windows environments. *Please remove:* `go test -v -race ./...` and simply have the program download one `.wet` file instead. 

- The shell commands `clean.sh` and `extract.sh` are tested in the continuous integration suite as Docker containers.

### Payment

- 1 ETH to someone who can meet the following requirements.

- Related to #5 which will have a 2.5 bounty for the CLI tool upon completion of the Docker Container.

### PR DESCRIPTION
**Pull request by iamonuwa**
Fixes #10

### CODE REVIEW

**Comment by iamonuwa** [comment]
@ChrisCates please take a look

**Comment by ChrisCates** [comment]
@iamonuwa, this looks excellent and well done.
Would it be possible to test it as a Dockerfile instead in Travis?

Once that change is made I will make sure to have the money released to your account after I test it myself and approve the changes.

**Comment by iamonuwa** [comment]
> Would it be possible to test it as a Dockerfile instead in Travis?
> 

Hi can you explain what you mean by test as Dockerfile and not travis please?

**Comment by ChrisCates** [comment]
@iamonuwa, in the Travis builds. The program should be able to run in Linux, Unix, and Windows as a Docker Container.

This link may prove useful: https://docs.travis-ci.com/user/docker/
If you need further clarification. Let me know!

**Comment by iamonuwa** [comment]
@ChrisCates ATM, docker for macos is not supported. Will it be okay to work with windows and linux?

**Comment by ChrisCates** [comment]
@iamonuwa, yes, it's okay. As long as I am able to run it on my own Mac OS computer.

Thank you for catching that. Appreciated.

**Comment by iamonuwa** [comment]
Sweet! Making changes now

**Comment by iamonuwa** [comment]
@ChrisCates please take a look

**Comment by ChrisCates** [comment]
@iamonuwa, almost at the finish line: https://travis-ci.org/ChrisCates/CommonCrawler/jobs/528564834

Also, the Travis-CI config should be able to run it as `go run src/*.go` and pass, I've left it up to you to decide how that should be executed as a Docker container. I've updated the repository to ensure that you can compile it with the specified command I provided, so please pull from the master branch if you have any questions we can discuss further.

Once that's sorted out. Will close and pay you the bounty. Keep up the great work, will have more coming next week.

Review #1 and #5 and let me know if you are interested in those tasks.

**Comment by iamonuwa** [comment]
> @iamonuwa, almost at the finish line: https://travis-ci.org/ChrisCates/CommonCrawler/jobs/528564834
> 
> Also, the Travis-CI config should be able to run it as `go run src/*.go` and pass, I've left it up to you to decide how that should be executed as a Docker container. I've updated the repository to ensure that you can compile it with the specified command I provided, so please pull from the master branch if you have any questions we can discuss further.
> 
> Once that's sorted out. Will close and pay you the bounty. Keep up the great work, will have more coming next week.
> 
> Review #1 and #5 and let me know if you are interested in those tasks.

For the failure, its because docker is currently not supported on macos.

Do you need me to allow it to run through `go run src/*.go` if its OSX?

I'll go through the issues.

**Comment by iamonuwa** [comment]
@ChrisCates I'll start with #5 now.

**Comment by ChrisCates** [comment]
The CI test you provided for OSX was great and what I wanted.
Keep it up, we will discuss #1, #5, #13 Friday.

**Pull request merged**
