### PR TITLE
#13 Full usage as a library

### PR DESCRIPTION
**Pull request by jay-dee7**

### CODE REVIEW

**Comment by jay-dee7** [comment]
@ChrisCates this fixes #13

**Comment by jay-dee7** [comment]
@ChrisCates does this still qualify for the bounty mentioned in the issue #13

**Comment by ChrisCates** [comment]
Hey @jay-dee7, let me check it now. Just need to sort out a few things.
I can add a bit more to the bounty if what you provided is good.

The project is still on hold. But, keep in touch. I will be restarting it soon.
You actually came just 1 1/2 months early before the project restarting after hiatus.

**Comment by ChrisCates** [comment]
Let me sort out some things.
I need to fund the project with a bounty too.

**Comment by jay-dee7** [comment]
@ChrisCates  yeah sure, i didnt really make any logical changes but made it modularized, added go modules, so apprently after this PR, it should be already be: 
* go get-able
* usable as a library
* go install would install it as a cli too (didn't add cobra/etc)

**Pull request closed without merging**
